name: CI/CD Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      # Step 3: Compile Java projects without tests
      - name: Compile Java projects
        run: mvn package -Dmaven.test.skip -f pom.xml

      # Log in to DockerHub (Optional: remove if not pushing to DockerHub)
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Set up Docker for CI environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      # Step 7: Build the Docker image for the app service
      - name: Build app service image
        run: |
          docker-compose -f docker-compose.yml build

      # Step 8: Push the Docker image to DockerHub
      - name: Push app service image
        run: |
          docker-compose -f docker-compose.yml push --verbose # Add verbose output